apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
  namespace: todocoder
  annotations: 
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: provisioner-nfs-storage #这里的名称要和provisioner配置文件中的环境变量PROVISIONER_NAME保持一致
parameters:
  archiveOnDelete: "false"

